# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RjQo5e7HDkcJyNGywQVYm-TeUiKkvYzY
"""

!pip install sentence_transformers

from sentence_transformers import SentenceTransformer, util
import numpy as np


book_descriptions = [
    "This book is about the adventures of a young wizard named Harry Potter.",
    "A classic novel exploring the complexities of human nature and society.",
    "A thrilling mystery set in the heart of New York City.",
    "A heartwarming tale of friendship and self-discovery in a small town.",
    "An epic fantasy saga filled with magic, dragons, and ancient prophecies."
    "Set in a poverty-stricken Glasgow in the early 1980s, Douglas Stuart’s Booker Prize-winning debut is a heartbreaking story which lays bare the ruthlessness of poverty and the limits of love. Agnes Bain has always dreamed of greater things, but when her husband abandons her she finds herself trapped in a decimated mining town with her three children, and descends deeper and deeper into drink. Her son Shuggie tries to help Agnes long after her other children have fled, but he too must abandon her to save himself. Shuggie is different, and he is picked on by the local children and condemned by adults. But he believes that if he tries his hardest he can escape this hopeless place.",
    "One of the most controversial and talked-about novels in modern history, American Psycho is the story of Patrick Bateman, a New York City high-flier with a penchant for fine wines, slickly cut suits and brutal murder. As Bateman's obsession with his hedonistic passions comes to a head, he descends into madness, with macabre and darkly comedic repercussions. Read more about the controversial history of American Psycho.",
    "Written in 1985, Blood Meridian is set in the anarchic world opened up by America’s westward expansion. Through the hostile landscape of the Texas–Mexico border wanders the Kid, a fourteen year-old Tennessean who is quickly swept up in the relentless tide of blood. But the apparent chaos is not without its order: while Americans hunt Indians – collecting scalps as their bloody trophies – they too are stalked as prey. Powerful, mesmerizing and savagely beautiful, Blood Meridian is considered one of the most important works in American fiction of the last century.",
    "Named one of BBC's 100 Novels That Shaped Our World, a copy of Pride and Prejudice is a worthy addition to any bookshelf. The story shows how the headstrong Elizabeth Bennet and the aristocratic Mr Darcy must have their pride humbled and their prejudices dissolved before they can acknowledge their love for each other. Jane Austen serves up laughs, romance, sharp observations, life lessons and characters that still feel vividly alive today. A universally acknowledged classic.",
    "A dark, haunting tale of passionate and destructive love, Wuthering Heights is one of the great romantic novels of the nineteenth century. Cathy and Heathcliff form an intense bond, but despite their love Cathy marries a rich suitor. But neither can forget the other, and while Cathy becomes increasingly unhappy, Heathcliff is driven by a lust for revenge that will echo through generations. Set against the backdrop of the Yorkshire moors, this is a dark novel with complicated characters who will hover doggedly in your thoughts long after the final page. ",
    "Despite selling less than 20,000 copies in the first year of its publication, The Great Gatsby is now established as a literary classic. Gatsby lives mysteriously in a luxurious Long Island mansion, playing lavish host to hundreds of people. And yet no one seems to know him or how he became so rich. But Gatsby cares for one person alone – Daisy Buchanan. Little does he know that his infatuation will lead to tragedy and end in murder. A glittering but cynical portrait of the American Dream that beautifully captures the flamboyance and cruelty of America's Jazz Age, it is no wonder Fitzgerald’s novel has been adapted so many times.",
]


model = SentenceTransformer('paraphrase-MiniLM-L6-v2')


description_embeddings = model.encode(book_descriptions, convert_to_tensor=True)


similarity_matrix = util.pytorch_cos_sim(description_embeddings, description_embeddings).numpy()


print("Similarity Matrix:")
print(similarity_matrix)

from sentence_transformers import SentenceTransformer, util
import numpy as np


book_descriptions = [
    "This book is about the adventures of a young wizard named Harry Potter.",
    "A classic novel exploring the complexities of human nature and society.",
    "A thrilling mystery set in the heart of New York City.",
    "A heartwarming tale of friendship and self-discovery in a small town.",
    "An epic fantasy saga filled with magic, dragons, and ancient prophecies."
    "Set in a poverty-stricken Glasgow in the early 1980s, Douglas Stuart’s Booker Prize-winning debut is a heartbreaking story which lays bare the ruthlessness of poverty and the limits of love. Agnes Bain has always dreamed of greater things, but when her husband abandons her she finds herself trapped in a decimated mining town with her three children, and descends deeper and deeper into drink. Her son Shuggie tries to help Agnes long after her other children have fled, but he too must abandon her to save himself. Shuggie is different, and he is picked on by the local children and condemned by adults. But he believes that if he tries his hardest he can escape this hopeless place.",
    "One of the most controversial and talked-about novels in modern history, American Psycho is the story of Patrick Bateman, a New York City high-flier with a penchant for fine wines, slickly cut suits and brutal murder. As Bateman's obsession with his hedonistic passions comes to a head, he descends into madness, with macabre and darkly comedic repercussions. Read more about the controversial history of American Psycho.",
    "Written in 1985, Blood Meridian is set in the anarchic world opened up by America’s westward expansion. Through the hostile landscape of the Texas–Mexico border wanders the Kid, a fourteen year-old Tennessean who is quickly swept up in the relentless tide of blood. But the apparent chaos is not without its order: while Americans hunt Indians – collecting scalps as their bloody trophies – they too are stalked as prey. Powerful, mesmerizing and savagely beautiful, Blood Meridian is considered one of the most important works in American fiction of the last century.",
    "Named one of BBC's 100 Novels That Shaped Our World, a copy of Pride and Prejudice is a worthy addition to any bookshelf. The story shows how the headstrong Elizabeth Bennet and the aristocratic Mr Darcy must have their pride humbled and their prejudices dissolved before they can acknowledge their love for each other. Jane Austen serves up laughs, romance, sharp observations, life lessons and characters that still feel vividly alive today. A universally acknowledged classic.",
    "A dark, haunting tale of passionate and destructive love, Wuthering Heights is one of the great romantic novels of the nineteenth century. Cathy and Heathcliff form an intense bond, but despite their love Cathy marries a rich suitor. But neither can forget the other, and while Cathy becomes increasingly unhappy, Heathcliff is driven by a lust for revenge that will echo through generations. Set against the backdrop of the Yorkshire moors, this is a dark novel with complicated characters who will hover doggedly in your thoughts long after the final page. ",
    "Despite selling less than 20,000 copies in the first year of its publication, The Great Gatsby is now established as a literary classic. Gatsby lives mysteriously in a luxurious Long Island mansion, playing lavish host to hundreds of people. And yet no one seems to know him or how he became so rich. But Gatsby cares for one person alone – Daisy Buchanan. Little does he know that his infatuation will lead to tragedy and end in murder. A glittering but cynical portrait of the American Dream that beautifully captures the flamboyance and cruelty of America's Jazz Age, it is no wonder Fitzgerald’s novel has been adapted so many times.",
]


model = SentenceTransformer('paraphrase-MiniLM-L6-v2')


description_embeddings = model.encode(book_descriptions, convert_to_tensor=True)


similarity_matrix = util.pytorch_cos_sim(description_embeddings, description_embeddings).numpy()


percentage_similarity_matrix = (similarity_matrix + 1) * 50  # Normalize to range [0, 100]


print("Percentage Similarity Matrix:")
print(percentage_similarity_matrix)
